<?
$PERM["/"]["8"]="W";
$PERM["/"]["*"]="R";
$PERM["bitrix"]["8"]="D";
$PERM["kabinet-prodavtsa"]["G2"]="R";
$PERM["kabinet-prodavtsa"]["G6"]="X";
$PERM["kabinet-pokupatelya"]["7"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>